# Generated by Django 4.2.2 on 2023-07-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0002_alter_booking_id_alter_image_id_alter_rating_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
