# Generated by Django 4.2.2 on 2023-07-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0003_booking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
