# Generated by Django 4.2.2 on 2023-07-31 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0004_booking_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
